### ISSUE TITLE
Can't metrics

### ISSUE THREAD

**Issue by PikaQiu520521** [arneschneuing/DiffSBDD#13]
from analysis.metrics import MoleculeProperties
mol_metrics = MoleculeProperties()
all_qed, all_sa, all_logp, all_lipinski, per_pocket_diversity = \
    mol_metrics.evaluate(pocket_mols)

Hi , I'm really need your help.I don't understand how to define the pocket_mols? Or if there have any examples?

**Comment by arneschneuing** [comment]
Hi, this function was made for evaluating generated molecules for different protein pockets. It expects a nested list of RDKit molecules. You need to store each pocket's molecule objects in a separate list and then gather all these lists into an outer list, which you can pass to `mol_metrics.evaluate()`. Is it clearer now?

**Comment by PikaQiu520521** [comment]
Hello, thank you for your previous question. Unfortunately, I was not able to fully replicate the process, but I used the same calculation method to evaluate the ligands generated by the model. I have two more questions now. 1. The generated ligand files have "row" and "processed" versions, as well as another folder containing paths and scores. I am not sure what they specifically mean. Could you provide some explanation? 2. The generated ligands do not have the bond relationships between atoms, so they are actually discrete points. How do you think about this issue?
