### ISSUE TITLE
GPU memory requirement for training

### ISSUE THREAD

**Issue by ChenShengsGitHub** [arneschneuing/DiffSBDD#14]
Hello, Awesome work! But when I tried to train the model I got _RuntimeError: CUDA out of memory_ for any batchsize>2, so I wonder what is the **GPU memory requirement** to reproduce your model training.

**Comment by WaltzofLeave** [comment]
Same problem. I'm running out of memory even setting batch_size=1. I'm using A6000 with 48G memory. I think there may be some memory leak ?

**Comment by WaltzofLeave** [comment]
#7 may help you.

**Comment by arneschneuing** [comment]
Hi @ChenShengsGitHub, does it work with a smaller `edge_cutoff`?
