### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by YaelZiv** [arneschneuing/DiffSBDD#15]
Hi,
Great work, thanks for sharing the code.
Can you give details about the provided checkpoints?
Were the checkpoints trained on the MOAD dataset?

**Comment by arneschneuing** [comment]
Hi, sorry for the delayed response.
The provided checkpoints are indeed from models trained on the MOAD dataset. So far, we only included them as examples but we are also planning to upload checkpoints for all other models at some point.
Best, Arne
