### ISSUE TITLE
process_ Crosslock.py  data preprocessing failed

### ISSUE THREAD

**Issue by xiaoxiannv999** [arneschneuing/DiffSBDD#18]
I have a question：In constants.py  154 rows，why is the amino_acid_dict equal {'C': 0, 'N': 1, 'O': 2, 'S': 3, 'B': 4, 'Br': 5, 'Cl': 6, 'P': 7, 'I': 8, 'F': 9}?
Maybe it causes this problem a problem when i run the command "python process_crossdock.py /home/admin641/gm/DiffSBDD --no_H --ca_only".

KeyError "'E' not in amino acid dict (/home/admin641/gm/DiffSBDD/crossdocked_pocket10/EXG1_CANAL_41_438_0/2pc8_A_rec_1eqc_cts_lig_tt_docked_6_pocket10.pdb, /home/admin641/gm/DiffSBDD/crossdocked_pocket10/EXG1_CANAL_41_438_0/2pc8_A_rec_1eqc_cts_lig_tt_docked_6.sdf)" EXG1_CANAL_41_438_0/2pc8_A_rec_1eqc_cts_lig_tt_docked_6_pocket10.pdb EXG1_CANAL_41_438_0/2pc8_A_rec_1eqc_cts_lig_tt_docked_6.sdf
#failed: 100: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 122.91it/s]
Traceback (most recent call last):
  File "/home/admin641/gm/DiffSBDD/process_crossdock.py", line 360, in <module>
    lig_coords = np.concatenate(lig_coords, axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

**Comment by xiaoxiannv999** [comment]
Can you briefly explain the reason why the residue coding is not used? Can I code the residue instead? I'm sorry to take up your time.

**Comment by yuanqidu** [comment]
Thanks for your question! The difference between Ca_only and full is just as the name suggests, full uses all atoms and Ca_only uses only the amino acids. We didn't use the residue since we have all fine-grained atom types but of course, the residue type could be included, too.

**Comment by yuanqidu** [comment]
Regarding the processing issue, thanks for spotting it, the amino_acid_dict should be the same as https://github.com/arneschneuing/DiffSBDD/blob/main/constants.py#L172. I will update the code correspondingly since for full atom representation, we use directly the atom types (C, H, O, N, etc.) so I missed this.

**Comment by xiaoxiannv999** [comment]
Thank you very much. I can run normally now.
