### ISSUE TITLE
Error when running the process_crossdock.py

### ISSUE THREAD

**Issue by WoohyunSonTMS** [arneschneuing/DiffSBDD#2]
Great work! 
I'm having a little trouble when I run the data processing program.
```
****
Invariant Violation
inconsistent state
Violation occurred on line 311 in file /home/conda/feedstock_root/build_artifacts/rdkit_1649923731950/work/Code/GraphMol/Canon.cpp
Failed Expression: ((firstFromAtom2->getBeginAtomIdx() == atom2->getIdx()) ^ (secondFromAtom2->getBeginAtomIdx() == atom2->getIdx()))
****


16957/16957 successful:  17%|█████████▎                                             | 16957/99929 [00:26<02:07, 649.32it/s]
Traceback (most recent call last):
  File "process_crossdock.py", line 378, in <module>
    train_smiles = compute_smiles(lig_coords, lig_one_hot, lig_mask)
  File "process_crossdock.py", line 126, in compute_smiles
    mol = Chem.MolToSmiles(mol)
RuntimeError: Invariant Violation
	inconsistent state
	Violation occurred on line 311 in file Code/GraphMol/Canon.cpp
	Failed Expression: ((firstFromAtom2->getBeginAtomIdx() == atom2->getIdx()) ^ (secondFromAtom2->getBeginAtomIdx() == atom2->getIdx()))
	RDKIT: 2022.03.1
	BOOST: 1_74
```

**Comment by HBioquant** [comment]
I also meet the trouble.
** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is /tmp/tmp6d1d0i03)

[04:06:37] 

****
Invariant Violation
inconsistent state
Violation occurred on line 306 in file /home/conda/feedstock_root/build_artifacts/rdkit_1603468918536/work/Code/GraphMol/Canon.cpp
Failed Expression: ((firstFromAtom2->getBeginAtomIdx() == atom2->getIdx()) ^ (secondFromAtom2->getBeginAtomIdx() == atom2->getIdx()))
****

16957/16957 successful:  17%|█████▎                         | 16957/99929 [00:50<04:08, 333.78it/s]
Traceback (most recent call last):
  File "process_crossdock.py", line 378, in <module>
    train_smiles = compute_smiles(lig_coords, lig_one_hot, lig_mask)
  File "process_crossdock.py", line 126, in compute_smiles
    mol = Chem.MolToSmiles(mol)
RuntimeError: Invariant Violation
	inconsistent state
	Violation occurred on line 306 in file Code/GraphMol/Canon.cpp
	Failed Expression: ((firstFromAtom2->getBeginAtomIdx() == atom2->getIdx()) ^ (secondFromAtom2->getBeginAtomIdx() == atom2->getIdx()))
	RDKIT: 2020.09.1
	BOOST: 1_74

**Comment by yuanqidu** [comment]
Thanks for letting us know. I have never met this before.
I suspect this might be a RDkit version issue. What RDkit version did you use and how did you install it?

**Comment by HBioquant** [comment]
Thanks for your reply, yuanqi,
As you can see in our comment, @WoohyunSonTMS's is 2022.03.1 and mine 2020.09.1.

**Comment by yuanqidu** [comment]
Sorry for the late response. This is because the molecule builder function uses openbabel as the default option to build molecules, while we used the make_mol_edm option before, we will update the code to throw the exceptions (in total 14 of them) soon.

https://github.com/arneschneuing/DiffSBDD/blob/main/analysis/molecule_builder.py#L130

**Comment by gcrth** [comment]
I also have the same problem, and I find the commit named "fix crossdocked preprocessing" does not solve this problem. I wonder if there will be another fix for this. Thank you.

**Comment by yuanqidu** [comment]
Thanks for raising the issue, you could simply put a try-except statement to discard those cases (in total 14 of them), I will find time to update this soon, sorry for the further delay, but I promise I will do it in a week!

**Comment by yuanqidu** [comment]
Thanks again for your patience, I have updated the code with the error-catching part.

**Comment by yuanqidu** [comment]
As there is no further comment, I will close this issue. Thanks again for the question!
