### ISSUE TITLE
how to get the right reference_ligand info

### ISSUE THREAD

**Issue by MachineGUN001** [arneschneuing/DiffSBDD#21]
I am trying to run it in colab notebook, using the new protein pdb file that was input. how do I enter the correct ligand information in the reference_ligand column? The ligand x information from the pdb file, when entered, does s not recognize it?

**Comment by arneschneuing** [comment]
The format should be `<chain_id>:<residue_idx>` (e.g. `A:330`), which specifies the chain and residue number the ligand can be found at in the PDB file.
Also, the 'reference_ligand' text box is an interactive cell. You don't need to run it again after changing its value (in case it caused any issues).

**Comment by MachineGUN001** [comment]
thanks for your explanation.
