### ISSUE TITLE
problem on 'config.yml'

### ISSUE THREAD

**Issue by prophet-Fang** [arneschneuing/DiffSBDD#3]
Hi arneschneuing,

Can you share your 'config.yml'?  These parameters in 'train.py' confused me a lot.

Thanks!

**Comment by arneschneuing** [comment]
Hi @prophet-Fang, have you seen the [example configuration file](https://github.com/arneschneuing/DiffSBDD/blob/bbba09eab521ffeceba3af435e2bb46cad8a4d9e/configs/example_config.yml)?
Is there a particular parameter that you're confused about?

**Comment by prophet-Fang** [comment]
That really helps a lot, thanks for your time!

**Comment by prophet-Fang** [comment]
Another question, why does 'pocket_one_hot' have a dimension of 10? (there are 20 kinds of amino acids)

**Comment by prophet-Fang** [comment]
Another question, why does 'pocket_one_hot' have a dimension of 10? (there are 20 kinds of amino acids)

**Comment by prophet-Fang** [comment]
> Another question, why does 'pocket_one_hot' have a dimension of 10? (there are 20 kinds of amino acids)

this result is acquired by running 'process_bindingmoad.py' on the bindingmoad dataset.

**Comment by arneschneuing** [comment]
If you run the script in full-atom mode, the pocket is represented by atoms and we use 10 different atom types.

**Comment by arneschneuing** [comment]
Hi, 
I am closing this issue now but feel free to re-open if you have further questions.
Best,
Arne
