### ISSUE TITLE
Error in Colab - "from lightning_modules import LigandPocketDDPM"

### ISSUE THREAD

**Issue by evancollins1** [arneschneuing/DiffSBDD#38]
Hi,

Upon running the exact Colab notebook included in the repo, I get an error in the code chunk entitled "Run sampling (this will take a few minutes; runtime depends on the input parameters n_samples, timesteps etc.)"

The error occurs on the line....
`from lightning_modules import LigandPocketDDPM`

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-9-efecae246c25>](https://localhost:8080/#) in <cell line: 7>()
      5 import torch
      6 import utils
----> 7 from lightning_modules import LigandPocketDDPM
      8 
      9 pdb_id = Path(pdbfile).stem

21 frames
[/usr/lib/python3.10/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

Could you help me with this issue? It appears similar to a previous [issue](https://github.com/arneschneuing/DiffSBDD/issues/11).

Thanks!

**Comment by arneschneuing** [comment]
Hi Evan,

thanks for reporting this issue. This [commit](https://github.com/arneschneuing/DiffSBDD/commit/61225b3f863afaaf75c574ebf30778d41fcb28e4) should solve it.

Best,
Arne
