### ISSUE TITLE
Problem on process_bindingmoad.py

### ISSUE THREAD

**Issue by lianghsun** [arneschneuing/DiffSBDD#5]
Hi there, thanks for an interesting implemantion of DiffSBDD. I have encountered the following problem when I try to preprocess the bindingmoad dataset:

```
#failed: 130: 100%|█████| 130/130 [00:00<00:00, 11105.76it/s]
Traceback (most recent call last):
  File "/home/user/Code/DiffSBDD/process_bindingmoad.py", line 571, in <module>
    lig_coords = np.concatenate(lig_coords, axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

How should I fix this problem? Thanks

**Comment by lianghsun** [comment]
OK, i figure out what happening. `basedir` should not contain `BindingMOAD_2020`. 😂

**Comment by OerthBio-Slav** [comment]
Can you explain how you solved this issue in more detail? Did you have the directory BindingMOAD_2020 in the same directory as your code? Did you modify the script somehow?
