### ISSUE TITLE
The initial ligand part

### ISSUE THREAD

**Issue by 1121091694** [arneschneuing/DiffSBDD#6]
Nice Paper，could you tell me how to add the atom and atomic coordinate of the initial ligand in the sample of protein pocket? Just like smiles seq2seq, we give the prompt of sequence like CCCC. In this work, can we give the initial ligand like atom and xyz
Could we generate the whole ligand with certain part which we can give

**Comment by arneschneuing** [comment]
Thank you! 
The [inpainting function](https://github.com/arneschneuing/DiffSBDD/blob/ca2d2ad4451893ec405308134fdffbe94e298b64/equivariant_diffusion/en_diffusion.py#L673) generally supports this. You can fix arbitrary parts of the pocket **or** ligand using the binary masks `lig_fixed` and `pocket_fixed`. Unfortunately, we have not implemented an interface for SDF/PDB files yet but it should look similar to the `generate_ligands` [function](https://github.com/arneschneuing/DiffSBDD/blob/ca2d2ad4451893ec405308134fdffbe94e298b64/lightning_modules.py#L687).
