### ISSUE TITLE
Config files for training publication models

### ISSUE THREAD

**Issue by Dunni3** [arneschneuing/DiffSBDD#8]
Hi,

Can you provide config files for the models that you trained for the publication? I'd like to be able to run your training script as it was run to produce publication results.

Congrats on putting out this awesome work and I appreciate the effort you've made to make this work accessible and reproducible.

Thanks,
Ian

**Comment by arneschneuing** [comment]
Hi Ian,

thanks for this suggestion. I uploaded config files for all five models presented in the preprint (c4dab2b6fb85e1b3db4482824db21d69dfd62db8). I would however ask @yuanqidu, who performed the CrossDocked experiments, to confirm that the settings are correct.

Best,
Arne

**Comment by Dunni3** [comment]
Awesome, thank you for the quick response.
